name: Static analysis

on: [push, pull_request]

jobs:
  psalm:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Analysis
        uses: docker://vimeo/psalm-github-actions